print("SJC23MCA-2006 : AJAY T M")
print("Batch : MCA 2023-25")
import numpy as np
A=np.array([[2,1,-2],[3,0,1],[1,1,-1]])
B=np.array([-3,5,-2])
x=np.linalg.solve(A,B)
print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("Solution of x:")
print(x)